import { useCallback, useRef, useState } from 'react';
import { ArrowRight, BookOpen, Check, CircleHelp, Clapperboard, FolderOpen, History, Lightbulb, Loader2, PanelTop, Plus, Save, Settings2, Sparkles, Square, Upload, X } from 'lucide-react';
import { useStudio, api } from './useStudio';
import { Button, Modal, SettingsModal } from './components';
import IdeaEditor from './IdeaEditor';
import OutlineEditor from './OutlineEditor';
import WritingEditor from './WritingEditor';
import StoryboardEditor from './StoryboardEditor';
import ExportEditor from './ExportEditor';

const steps = [{ name: '创作灵感', sub: 'IDEA', icon: Lightbulb }, { name: '故事纲要', sub: 'OUTLINE', icon: BookOpen }, { name: '文稿与角色', sub: 'STORY & CAST', icon: Sparkles }, { name: '分镜绘制', sub: 'STORYBOARD', icon: Clapperboard }, { name: '排版导出', sub: 'PUBLISH', icon: PanelTop }];
const statusNames = { completed: '已完成', partial: '部分完成', failed: '失败', cancelled: '已停止', interrupted: '已中断', queued: '等待中', running: '进行中', cancelling: '停止中' };
export default function App() {
  const s = useStudio(); const p = s.project;
  const [step, setStep] = useState(0), [showSettings, setShowSettings] = useState(false), [modal, setModal] = useState(''), [versions, setVersions] = useState([]), [home, setHome] = useState(false);
  const fileRef = useRef(null);
  const setError = s.setError;
  const report = useCallback(message => setError(message), [setError]);
  const act = fn => async (...args) => { try { return await fn(...args); } catch (e) { report(e.message); } };
  const run = act(async (type, target, note) => { if (s.settings?.provider !== "codex" && !s.settings?.hasKey) { setShowSettings(true); return; } await s.run(type, target, note); if (type === 'outline') setStep(1); });
  async function create(demo) { await s.create(demo); setHome(false); setStep(demo ? 1 : 0); }
  async function history() { await s.flush(); setVersions(await api(`/projects/${p.id}/versions`)); setModal('history'); }
  const completed = [!!p?.idea.trim(), !!p?.outlineApproved, !!p?.prose || p?.characters.some(c => c.reference), !!p?.panels.length && p.panels.every(x => x.image), false];
  const showHome = home || !p;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-symbol"><i /><i /><i /></span><div><strong>墨格</strong><span>MOGE STUDIO</span></div><small>2.1</small></div><div className="sidebar-caption">小说与漫画创作室</div><button className={`nav-home ${showHome ? 'active' : ''}`} disabled={s.busy} onClick={act(async () => { await s.flush(); await s.refresh(); setHome(true); })}><FolderOpen size={18} />我的作品</button><Button variant="new-project" icon={Plus} disabled={s.busy} onClick={act(() => create(false))}>新建短篇</Button><div className="library-label">最近的故事 <span>{s.projects.length}</span></div><nav className="project-list" aria-label="作品列表">{s.projects.map(item => <button key={item.id} disabled={s.busy} className={p?.id === item.id && !home ? 'active' : ''} onClick={act(async () => { await s.open(item.id); setHome(false); setStep(item.hasOutline ? 1 : 0); })}><span className="project-dot" /><div><strong>{item.id === p?.id ? p.title : item.title}</strong><small>{item.ready ? `${item.ready} 格已绘制` : item.hasOutline ? '已有故事纲要' : '从一个想法开始'}</small></div></button>)}{!s.projects.length && <p className="sidebar-empty">你的故事会珍藏在这里。<br />从第一份短篇开始吧。</p>}</nav><div className="sidebar-bottom"><div className="local-note"><span className="status-dot" /><div><strong>本地创作空间</strong><small>作品保存在这台电脑</small></div></div><button disabled={s.busy} onClick={() => fileRef.current.click()}><Upload size={17} />导入作品工程</button><button onClick={() => setModal('help')}><CircleHelp size={17} />创作指南</button><button disabled={s.busy} onClick={() => setShowSettings(true)}><Settings2 size={17} />生成连接<span className={`connection-dot ${(s.settings?.provider === 'codex' ? s.connection?.connected : s.settings?.hasKey) ? 'connected' : ''}`} /></button><span className="sidebar-footnote">每一个故事，都值得被看见。</span></div></aside><main className="main"><header className="topbar"><div className="breadcrumb"><span>创作空间</span><span>/</span><strong>{showHome ? '我的作品' : p.title}</strong></div><div className="row">{!showHome && <><span className={`save-status ${s.saving === 'error' ? 'bad' : ''}`}>{s.saving === 'saving' ? <Loader2 className="spin" size={13} /> : <Check size={13} />}{({ saved: '已保存到本机', dirty: '等待保存', saving: '正在保存', error: '保存失败' })[s.saving]}</span><Button icon={Save} disabled={s.busy} onClick={act(async () => { await s.flush(); await api(`/projects/${p.id}/versions`, { method: 'POST', body: { label: '手动保存版本' } }); s.setNotice('已保存一份可恢复的作品版本。'); })}>保存版本</Button><Button icon={History} disabled={s.busy} onClick={act(history)}>历史</Button></>}<span className="profile-mark">墨</span></div></header>
  <div className="workspace">{s.error && <div className="global-message error-box" role="alert"><span>{s.error}</span><button aria-label="关闭错误提示" className="icon-button" onClick={() => s.setError('')}><X size={16} /></button></div>}{s.notice && <div className="global-message success-box" role="status"><span>{s.notice}</span><button aria-label="关闭提示" className="icon-button" onClick={() => s.setNotice('')}><X size={16} /></button></div>}
  {s.loading ? <div className="loading-screen"><Loader2 className="spin" />正在打开创作空间…</div> : showHome ? <><section className="welcome"><div><span className="eyebrow">A LITTLE STORY. A WHOLE WORLD.</span><h1>让脑海里的故事，<br />在纸上相遇。</h1><p>从一闪而过的灵感，到有温度的文字与画面。<br />和 GPT 一起，完成属于你的短篇小说与漫画。</p><div className="row"><Button variant="primary" icon={Plus} onClick={act(() => create(false))}>开始一个新故事</Button><Button icon={ArrowRight} onClick={act(() => create(true))}>体验示例纲要</Button></div><small>示例只含预写的故事纲要，不消耗生成额度。</small></div><div className="welcome-art" aria-hidden="true"><div className="floating-page"><div className="page-lines"><i /><i /><i /></div><div className="mini-comic"><span className="night-scene"><i /></span><span className="day-scene"><i /></span><span className="wide-scene"><i /><b>故事，从这里开始。</b></span></div><span className="page-sign">MOGE / 001</span></div><span className="art-star star-one">✧</span><span className="art-star star-two">✳</span></div></section><div className="home-section-heading"><h2>你的创作旅程</h2><span>五个步骤，一个完整的短篇</span></div><div className="journey-cards">{steps.map((item, i) => <div key={i}><item.icon size={23} strokeWidth={1.4} /><small>0{i + 1}</small><h3>{item.name}</h3><p>{['留住一个好点子', '决定故事的走向', '细写文字，固定人物', '把每个瞬间画出来', '完成可以分享的作品'][i]}</p></div>)}</div>{s.projects.length > 0 && <><div className="home-section-heading"><h2>继续创作</h2><span>最近保存的作品</span></div><div className="project-cards">{s.projects.map(item => <button key={item.id} onClick={act(async () => { await s.open(item.id); setHome(false); setStep(item.hasOutline ? 1 : 0); })}><div className="project-cover">{item.cover ? <img src={item.cover} alt={item.title} /> : <BookOpen size={35} strokeWidth={1} />}</div><h3>{item.title}</h3><p>{new Date(item.updatedAt).toLocaleDateString('zh-CN')} · {item.ready}/{item.panelCount} 格已绘制</p></button>)}</div></>}</> : <><div className="workspace-heading"><div><span className="eyebrow">YOUR STORY, FRAME BY FRAME</span><h1>{steps[step].name}</h1></div><span className="tag">短篇创作 · {p.panelCount} 格计划</span></div><nav className="stepper" aria-label="创作步骤">{steps.map((item, i) => <button key={i} className={`${step === i ? 'active' : ''} ${completed[i] ? 'done' : ''}`} onClick={() => setStep(i)}><span className="step-num">{completed[i] && step !== i ? <Check size={15} /> : `0${i + 1}`}</span><span><strong>{item.name}</strong><small>{item.sub}</small></span>{i < 4 && <ArrowRight className="step-arrow" size={13} />}</button>)}</nav>{!(s.settings?.provider === 'codex' ? s.connection?.connected : s.settings?.hasKey) && <div className="setup-banner"><KeyIcon /><span>连接你的 ChatGPT 账号，即可通过官方 Codex 开始编剧和绘图。也可先自由编辑。</span><button onClick={() => setShowSettings(true)}>连接账号 <ArrowRight size={14} /></button></div>}{step > 1 && !p.outlineApproved && <div className="outline-warning"><BookOpen size={17} /><span>先到「故事纲要」确认创作方向，即可启用后续生成。</span><button onClick={() => setStep(1)}>查看纲要</button></div>}
  <fieldset className={`editor-fieldset ${s.busy ? 'generating-state' : ''}`} disabled={s.busy}>{step === 0 && <IdeaEditor p={p} update={s.update} run={run} next={() => setStep(1)} report={report} />}{step === 1 && <OutlineEditor p={p} update={s.update} run={run} next={act(async () => { await s.flush(); s.update({ outlineApproved: true }); await s.flush(); setStep(2); })} />}{step === 2 && <WritingEditor p={p} update={s.update} run={run} next={() => setStep(3)} report={report} />}{step === 3 && <StoryboardEditor p={p} update={s.update} run={run} job={s.job} />}{step === 4 && <ExportEditor p={p} update={s.update} flush={s.flush} report={report} />}</fieldset></>}
  </div>{s.busy && <div className="job-dock" role="status"><span className="job-icon"><Loader2 className="spin" size={22} /></span><div className="job-info"><strong>{s.job?.message || '准备创作…'}</strong><span>请稍候 · 图片生成可能需要数分钟 · 已完成内容自动保存</span><div className="job-track"><i style={{ width: `${s.job?.total ? s.job.progress / s.job.total * 100 : 0}%` }} /></div></div><span>{s.job?.progress || 0} / {s.job?.total || 1}</span><Button icon={Square} disabled={s.pending || s.job?.status === 'cancelling'} onClick={act(s.cancel)}>停止</Button></div>}</main>
  <input ref={fileRef} hidden type="file" accept=".json" onChange={act(async e => { const file = e.target.files[0]; e.target.value = ''; if (!file) return; if (file.size > 180 * 1024 * 1024) throw new Error('工程文件超过 180 MB，暂时无法导入。'); await s.importProject(JSON.parse(await file.text())); setHome(false); setStep(1); s.setNotice('作品已导入为一份新工程。'); })} />
  {showSettings && <SettingsModal settings={s.settings} disabled={s.busy} onClose={() => setShowSettings(false)} onSaved={s.setSettings} onConnection={s.setConnection} />}
  {modal === 'history' && <Modal title="作品历史与生成记录" wide onClose={() => setModal('')}><p className="muted">重新生成前自动保存版本。恢复会先备份当前作品。</p><div className="version-list">{versions.length ? versions.map(v => <div key={v.id}><History size={17} /><div><strong>{v.label}</strong><small>{new Date(v.createdAt).toLocaleString('zh-CN')}</small></div><Button onClick={act(async () => { const restored = await api(`/projects/${p.id}/restore/${v.id}`, { method: 'POST' }); s.accept(restored); await s.refresh(); setModal(''); s.setNotice('已恢复历史版本，恢复前的作品也已备份。'); })}>恢复</Button></div>) : <p className="small-note">尚无历史版本。点击「保存版本」即可创建。</p>}</div><h3 className="history-heading">生成记录</h3><div className="version-list">{s.jobs.map(j => <div key={j.id}><Clapperboard size={17} /><div><strong>{j.label} · {statusNames[j.status]}</strong><small>{j.message}</small><small>{new Date(j.createdAt).toLocaleString('zh-CN')} · {j.usage?.length || 0} 次已返回的模型调用</small></div></div>)}</div></Modal>}
  {modal === 'help' && <Modal title="从灵感，到一份短篇作品" wide onClose={() => setModal('')}><div className="guide">{steps.map((item, i) => <div key={i}><span>0{i + 1}</span><div><h3>{item.name}</h3><p>{['输入一个想法或粘贴小说片段，选择 4–12 格与画风。生成第一版故事纲要。', '修改一句话故事、背景、冲突、节拍和结尾，然后点击确认。重写纲要会重置后续内容，并保留历史。', '按需生成或手写短篇文段。固定角色发型、服装和道具；上传或生成参考图。文稿可以跳过。', '先生成可编辑脚本，再逐格或批量绘图。每格可改镜头、对白、出场角色；可重绘并选择历史图片。', '选择双列、主视觉或长条布局，调整中文气泡，导出 PNG、PDF、文稿和带图片的可编辑工程。'][i]}</p></div></div>)}<div className="privacy-note"><p>作品、素材与历史版本保存在本机。默认通过官方 Codex 使用 ChatGPT 订阅额度，登录凭据由 Codex 管理。只有主动选择 API 模式才使用单独计费的 API 密钥。未连接时可以编辑与体验示例。</p></div><p className="small-note">停止只能中止本地等待和后续绘制，已提交的请求仍可能消耗额度或产生 API 费用。关闭程序会中断进行中的任务，重启后可继续绘制缺失画格。</p></div></Modal>}
  </div>;
}
function KeyIcon() { return <Settings2 size={17} />; }
