import { useRef } from 'react';
import { ArrowRight, Check, Sparkles, Upload, WandSparkles } from 'lucide-react';
import { STYLES } from '../shared/story';
import { Button, Field } from './components';

export default function IdeaEditor({ p, update, run, next, report }) {
  const fileRef = useRef(null);
  const ideas = ['一家只在雨夜营业的修伞店，替客人修复的其实是与某个人告别的记忆。围绕一把黄色旧伞，写一个温柔的反转。', '退休宇航员每天给月球写信。搬家那天，他在门口收到一封落款为月亮的回信。只用两个角色、一个场景，写一个轻科幻片段。', '猫咪第一次独自在家，决定帮主人整理书桌。把一次小小的混乱写成四格喜剧，最后给出出人意料的温情结尾。'];
  return <div className="idea-layout"><div><section className="paper idea-paper"><div className="section-title"><span className="eyebrow">THE FIRST SPARK</span><span className="tag">一个片段，也可以很动人</span></div><h2>从你的一个想法开始。</h2><p className="muted">人物、一个场景、一句对白，或一段已有小说。<br />先写下来，我们一起找到故事的起承转合。</p><Field label="你想讲一个怎样的故事？"><textarea className="idea-input" maxLength={30000} placeholder="例如：末班公交上，一个老人提着装满星星的玻璃罐。他说，这是乘客们没说出口的心愿……" value={p.idea} onChange={e => update({ idea: e.target.value, outlineApproved: false })} /></Field><div className="input-footer"><button className="text-button" onClick={() => fileRef.current.click()}><Upload size={14} />导入小说文段</button><span>{p.idea.length.toLocaleString()} / 30,000</span></div><input ref={fileRef} type="file" accept=".txt,.md" hidden onChange={async e => { const f = e.target.files[0]; if (f) { if (f.size > 120000) report('文段文件过大，请选择 30,000 字以内的片段。'); else { const text = await f.text(); if (text.length > 30000) report('文段超过 30,000 字，已载入前 30,000 字。'); update({ idea: text.slice(0, 30000), outlineApproved: false }); } } e.target.value = ''; }} />
    <div className="field-grid"><Field label="故事类型"><select value={p.genre} onChange={e => update({ genre: e.target.value })}>{['温暖治愈', '悬疑反转', '轻科幻', '奇幻冒险', '生活喜剧', '爱情片段', '古风志怪', '自定义'].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="情绪与叙事语气"><input maxLength={500} value={p.tone} onChange={e => update({ tone: e.target.value })} placeholder="温柔、克制，有一点幽默" /></Field></div>
    <div className="section-rule" /><h3>给故事一个恰好的长度</h3><p className="muted">聚焦一个冲突、一次转折、一个有回响的结尾。</p><div className="length-choices">{[{ n: 4, title: '四格片段', text: '轻巧完整 · 一个瞬间' }, { n: 6, title: '六格短篇', text: '铺垫转折 · 节奏从容' }, { n: 8, title: '八格故事', text: '细腻的情绪与动作' }, { n: 12, title: '十二格短篇', text: '更有层次的片段' }].map(item => <button key={item.n} className={`length-card ${p.panelCount === item.n ? 'selected' : ''}`} onClick={() => update({ panelCount: item.n })}><span className="length-icon">{Array.from({ length: 4 }, (_, i) => <i key={i} />)}</span><strong>{item.title}</strong><small>{item.text}</small>{p.panelCount === item.n && <Check className="choice-check" size={15} />}</button>)}</div>
    <div className="idea-cta"><span><Sparkles size={15} />先确认纲要，再开始绘制</span><Button variant="primary" icon={p.outline ? ArrowRight : WandSparkles} disabled={!p.outline && p.idea.trim().length < 8} onClick={() => p.outline ? next() : run('outline')}>{p.outline ? '查看故事纲要' : '生成故事纲要'}</Button></div></section><div className="inspiration"><span>还没有灵感？试试这些开头</span>{ideas.map((idea, i) => <button key={i} onClick={() => update({ idea, outlineApproved: false })}>{['雨夜修伞店', '来自月亮的信', '猫的整理计划'][i]}<ArrowRight size={13} /></button>)}</div></div>
    <aside className="direction-card"><span className="eyebrow">ART DIRECTION</span><h3>选择你的视觉语言</h3><p>角色和每一格画面都会沿用这一画风。</p><div className="style-grid">{STYLES.map((s, i) => <button key={s.id} className={`style-card ${p.styleId === s.id ? 'selected' : ''}`} onClick={() => update({ styleId: s.id })}><div className={`style-art art-${i}`} style={{ '--art-color': s.color }}><span className="art-moon" /><span className="art-hill" /><span className="art-person" />{p.styleId === s.id && <b><Check size={13} /></b>}</div><strong>{s.name}</strong><small>{s.note}</small></button>)}</div><Field label="补充画风要求（可选）"><textarea rows={2} maxLength={3000} placeholder="暖黄灯光、蓝灰夜色、留白" value={p.customStyle} onChange={e => update({ customStyle: e.target.value })} /></Field><div className="small-note">风格卡为视觉示意。实际插画将在分镜确认后生成。</div></aside></div>;
}
