import { useState } from 'react';
import { ArrowRight, BookOpen, Check, CheckCheck, Pencil, RefreshCw, Sparkles } from 'lucide-react';
import { Button, Empty, Field } from './components';
export default function OutlineEditor({ p, update, run, next }) {
  const [note, setNote] = useState('');
  if (!p.outline) return <Empty icon={BookOpen} title="先让故事有一个清晰的方向" action={<Button variant="primary" icon={Sparkles} disabled={p.idea.trim().length < 8} onClick={() => run('outline')}>根据思路生成纲要</Button>}>填写创作思路后，GPT 会整理人物、核心冲突与起承转合。</Empty>;
  const o = p.outline;
  const edit = patch => update({ outline: { ...o, ...patch }, outlineApproved: false });
  return <div className="outline-layout"><section className="paper manuscript"><div className="section-title"><span className="eyebrow">STORY OUTLINE</span><span className={`tag ${p.outlineApproved ? 'green' : ''}`}>{p.outlineApproved ? '纲要已确认' : '等待你的审阅'}</span></div><Field label="作品标题"><input className="title-input" maxLength={160} value={p.title} onChange={e => update({ title: e.target.value, outline: { ...o, title: e.target.value }, outlineApproved: false })} /></Field><Field label="一句话故事"><textarea className="logline" rows={2} value={o.logline} onChange={e => edit({ logline: e.target.value })} /></Field><div className="field-grid"><Field label="时空与场景"><textarea rows={3} value={o.setting} onChange={e => edit({ setting: e.target.value })} /></Field><Field label="核心冲突"><textarea rows={3} value={o.conflict} onChange={e => edit({ conflict: e.target.value })} /></Field></div><div className="section-rule" /><h3>故事节拍</h3><div className="beats">{o.beats.map((b, i) => <div className="beat" key={i}><span className="beat-number">0{i + 1}</span><div><input aria-label={`第${i + 1}个节拍标题`} value={b.label} onChange={e => edit({ beats: o.beats.map((x, j) => j === i ? { ...x, label: e.target.value } : x) })} /><textarea aria-label={`第${i + 1}个节拍内容`} rows={3} value={b.text} onChange={e => edit({ beats: o.beats.map((x, j) => j === i ? { ...x, text: e.target.value } : x) })} /></div></div>)}</div><Field label="结尾与余韵"><textarea rows={3} value={o.ending} onChange={e => edit({ ending: e.target.value })} /></Field></section><aside className="aside-stack"><div className="paper"><span className="eyebrow">YOUR CREATIVE CONTROL</span><h3>故事，由你定稿</h3><p className="muted">左侧内容都可以直接修改。确认方向后，再写成文段或转成漫画分镜。</p><ul className="check-list"><li><Check size={15} />一个聚焦的短篇片段</li><li><Check size={15} />清晰的动机与转折</li><li><Check size={15} />可以被画出来的情节</li><li><Check size={15} />有收束的结尾</li></ul>{!p.outlineApproved && (p.prose || p.panels.length > 0) && <p className="inline-warning">纲要有待确认。现有文稿与画格已保留，请重新核对它们是否符合新纲要。</p>}<Button variant="primary full" icon={p.outlineApproved ? ArrowRight : CheckCheck} onClick={next}>{p.outlineApproved ? '前往文稿与角色' : '确认纲要，继续创作'}</Button></div><div className="paper"><h3><Pencil size={16} />和编剧再聊一句</h3><Field label="纲要修改意见"><textarea rows={4} placeholder="保留相遇场景，但把结尾改得更有悬念。" value={note} onChange={e => setNote(e.target.value)} /></Field><Button variant="full" icon={RefreshCw} onClick={() => run('outline', null, note)}>重新构思纲要</Button><p className="small-note">重新构思会建立历史版本，并清空当前文稿和分镜，以便围绕新故事创作。</p></div></aside></div>;
}
